version: '3.9'


services:
  db:
    image: postgres:14-alpine
    # ports:
    #   - '5432:5432'

    environment:
      # - POSTGRES_PASSWORD=admin
      # - POSTGRES_USER=satisfaction
      # - POSTGRES_DB=cafe_project_db

      - DJANGO_DB_URL=psql://satisfaction:admin@db:5432/cafe_project_db
    expose:
      - 5432
    volumes:
      # - ./data/db:/var/lib/postgresql/data/
      - ./backend/:/db.sqlite3
    networks:
      - db-net

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile

    ports:
      - '3000:3000'

    volumes:
      - ./frontend:/app/frontend

    depends_on:
      - backend
    links:
      - backend:backend
    networks:
      - db-net

  backend:
    # command: python3 manage.py runserver 0.0.0.0:8000
    build: 
      context: ./backend
      dockerfile: Dockerfile

    environment:
    # - POSTGRES_PASSWORD=admin
    # - POSTGRES_USER=satisfaction
    # - POSTGRES_DB=cafe_project_db

    - DJANGO_DB_URL=psql://satisfaction:admin@db:5432/cafe_project_db

    ports:
      - '8000:8000'

    volumes:
      - ./backend:/app/backend

    depends_on:
      - db
    links:
      - db:db
    networks:
      - db-net

networks:
  db-net:
    driver: bridge