# Generated by Django 4.1.5 on 2023-01-17 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=255, unique=True)),
                ('depth', models.PositiveIntegerField()),
                ('numchild', models.PositiveIntegerField(default=0)),
                ('preview', models.ImageField(blank=True, null=True, upload_to='')),
                ('alt', models.CharField(blank=True, max_length=50, null=True, verbose_name='Alternative preview name')),
                ('name', models.CharField(max_length=50, verbose_name='Category name')),
                ('slug', models.SlugField(verbose_name='Slug for category')),
                ('short_overview', models.TextField(blank=True, max_length=250, null=True, verbose_name='Category short overview')),
                ('visibility', models.BooleanField(blank=True, default=True, null=True, verbose_name='Category visibility on main page')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
