# Generated by Django 4.1.4 on 2022-12-21 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preview', models.ImageField(blank=True, null=True, upload_to='shared/media/', verbose_name='Gallery preview')),
                ('alt', models.CharField(blank=True, max_length=50, null=True, verbose_name='Gallery preview alternative name')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='shared/media/', verbose_name='Gallery picture')),
                ('alt', models.CharField(blank=True, max_length=50, null=True, verbose_name='Picture alternative name')),
                ('my_order', models.PositiveIntegerField(default=0)),
                ('gallery', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='image_set', to='gallery.gallery', verbose_name='Gallery foreignkey')),
            ],
            options={
                'ordering': ['my_order'],
            },
        ),
    ]
