# Generated by Django 3.2.16 on 2023-06-20 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0003_gallery_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='preview',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Gallery preview'),
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Gallery picture'),
        ),
    ]
