# Generated by Django 4.1.4 on 2022-12-10 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preview', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Product preview')),
                ('img_alt', models.CharField(blank=True, max_length=25, null=True, verbose_name='Alternative product preview name')),
                ('name', models.CharField(max_length=100, verbose_name='Product name')),
                ('slug', models.SlugField(blank=True, max_length=100, null=True, unique=True, verbose_name='Slug product')),
                ('price', models.PositiveIntegerField(verbose_name='Product price ')),
                ('old_price', models.PositiveIntegerField(blank=True, null=True, verbose_name='Old price ')),
                ('overview', models.TextField(blank=True, max_length=1000, null=True, verbose_name='Product overview')),
                ('new_product', models.BooleanField(blank=True, default=True, null=True, verbose_name='New product')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Product creation date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Product update date')),
                ('my_order', models.PositiveIntegerField(default=0)),
                ('related_products', models.ManyToManyField(blank=True, to='product.product', verbose_name='Related products')),
            ],
            options={
                'ordering': ['my_order'],
            },
        ),
    ]
