# Generated by Django 3.2.16 on 2023-02-15 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='related_products',
            field=models.ManyToManyField(blank=True, related_name='_product_product_related_products_+', to='product.Product', verbose_name='related products'),
        ),
    ]
